<a href="https://colab.research.google.com/github/sharjil-d/TensorFlow_Google_Colab/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('welcome to tensor flow')

welcome to tensor flow


We are going to cover
intro to tensors
getting info from tensors
manipulating tensors
tensors & numpy
using @tf.function
using GPU with tensor flow

In [ ]:
#intro to tensor
import tensorflow as tf
print(tf.__version__)


2.12.0


In [ ]:
# create tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check number of dimensions of a tensor
scalar.ndim

0

In [ ]:
# create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#check the dimension of vector
vector.ndim

1

In [ ]:
#create a matrix
matrix=tf.constant([[10,7],[7,17]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 17]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# create another matrix
another_matrix=tf.constant([
    [10.,7.],
    [3.,2.],
    [4.,1.]

],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 4.,  1.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# let's create a tensor
tensor=tf.constant([
    [
        [1,2,3],
        [3,4,5]
    ],
     [
        [1,2,3],
        [3,4,5]
    ]
])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [3, 4, 5]],

       [[1, 2, 3],
        [3, 4, 5]]], dtype=int32)>

In [ ]:
tensor.ndim

3

# tf variable

In [ ]:
# create the same tensor with tf.variable
changable_tensor=tf.Variable([10,7])
unchangable_tensor=tf.constant([10,7])
(changable_tensor,unchangable_tensor)

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changable_tensor[0]=2
changable_tensor

TypeError: ignored

In [ ]:
# try with .assign
changable_tensor[0].assign(2)
changable_tensor

In [ ]:
# lets try to change unchangable tensor
unchangable_tensor[0].assign(7)
unchangable_tensor

Create random tensors

In [ ]:
#create two random (but the same) tensors

random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,4))
random_2=tf.random.Generator.from_seed(42)
random_2=tf.random.normal(shape=(3,4))

random_1,random_2,random_1 == random_2

NameError: ignored

In [ ]:
## shuffle the order of elements in a tensor
not_shuffled=tf.constant([
      [1,2],[3,4],[5,6]
  ])
not_shuffled

In [ ]:
# shuffle the not shuffle
tf.random.set_seed=42
tf.random.shuffle(not_shuffled,seed=42)


Other ways to create tensors

In [ ]:
tf.ones([10,7])

In [ ]:
# tensor of all zeros
tf.zeros(shape=(2,2))

In [ ]:
# we can also turn numpy arrays into tensorflow

import numpy as np

numpy_A=np.arange(1,25,dtype=int)  # create vector aaray
numpy_A

In [ ]:
A=tf.constant(numpy_A,shape=(2,4,3))
A.shape

Getting info from tensors
shape
rank
axis or dimension
size


In [ ]:
#create a rank 4 tensor(4 dimensions)

rank_4_tensor=tf.zeros([2,3,4,5])
rank_4_tensor

In [ ]:
rank_4_tensor[0]

In [ ]:
rank_4_tensor[-1]

Tensors can be indexed just like python lists

In [ ]:
rank_4_tensor[:2,:2,:2,:2]

In [ ]:
# get first element from each dimension from each index
rank_4_tensor[:2,:3,:1,:1]

In [ ]:
# get first element from each dimension from each index except the final one
rank_4_tensor[:1,:1,:1]


In [ ]:
rank_4_tensor[:1,:1,:,:1]

In [ ]:
rank_2_tensor=tf.constant([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
rank_2_tensor

In [ ]:
# get the last item of each row
rank_2_tensor[:,-1]

In [ ]:
# add in extra dimension to rank 2 tensor

#rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor=rank_2_tensor[:,:,tf.newaxis]  #above and below, both are same
rank_3_tensor

In [ ]:
# alternative to tf.new axis
tf.expand_dims(rank_2_tensor,axis=1)

In [ ]:
tf.expand_dims(rank_2_tensor,axis=0)

Manipulating tensors


1.   +,-,*,/



In [ ]:
tensor=tf.constant([
    [10,7],[3,4]
])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tensor=tensor+10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# multiplication
tensor=tensor*2
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[40, 34],
       [26, 28]], dtype=int32)>

In [ ]:
# we can inbult functions as well
tensor=tf.multiply(tensor,3)
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[120, 102],
       [ 78,  84]], dtype=int32)>

In [ ]:
tensor=tf.add(tensor,3)
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[123, 105],
       [ 81,  87]], dtype=int32)>

Matrix multiplication


In [ ]:
tensor=tf.constant([
    [10,7],[3,4]
])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# matrix multiplication using python @ perator
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
X=tf.constant([
    [1,2],[3,4],[5,6]
])

In [ ]:
# transpose
X,tf.transpose(X),tf.reshape(X,shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

Dot product
Matrix multiplication also referred as dot product

In [ ]:
tensor=tf.constant([
    [10,7],[3,4]
])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tf.tensordot(tensor,tensor,axes=1),tensor@tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]], dtype=int32)>)

# changing type of tensor

In [ ]:
t1=tf.constant([10.7,3.7])
t1.dtype

tf.float32

In [ ]:
#changing from 32 bit to 16 bit
t2=tf.cast(t1,dtype=tf.float16)
t2

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([10.7,  3.7], dtype=float16)>

In [ ]:
C=tf.cast(t2,dtype=tf.int32)
C

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  3], dtype=int32)>

Aggregating tensors

In [ ]:

D=tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# get absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
# get minimum, maxmum, mean, sum
t=tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [ ]:
tf.reduce_min(t),tf.reduce_max(t),tf.reduce_mean(t),tf.reduce_sum(t)

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=9>,
 <tf.Tensor: shape=(), dtype=int32, numpy=5>,
 <tf.Tensor: shape=(), dtype=int32, numpy=45>)

In [ ]:
# find variance
import tensorflow_probability as tfp

In [ ]:
tfp.stats.variance(t)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([6, 6, 6], dtype=int32)>

In [ ]:
tf.math.reduce_variance(tf.cast(t,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=6.6666665>

In [ ]:
tf.math.reduce_std(tf.cast(t,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=2.5819888>

In [ ]:
tf.random.set_seed(42)
t=tf.random.uniform(shape=[50])

In [ ]:
t

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# find positional max
tf.argmax(t)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# index on largest value position
t[tf.argmax(t)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# check equality
t[tf.argmax(t)]==tf.reduce_max(t)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

# squeezing a tensor(removing all single dimansion)

In [ ]:
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,50))

In [ ]:
G

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [ ]:
G_squeezed=tf.squeeze(G)
G_squeezed,G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

One-hot encoding

In [ ]:
# create list of indicis
some_list=[0,1,2,3]
#one hot encode
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

# connect to GPU


In [ ]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Mon Jun 26 07:07:06 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P8     9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------